'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AlimentoComponente
    Public Property IDAliCom As Integer
    Public Property AliComValor As Nullable(Of Decimal)
    Public Property FKIDAli As Integer
    Public Property FKIDCom As Integer
    Public Property FKIDCat As Integer
    Public Property FKIDEstVal As Integer

    Public Overridable Property Alimento As Alimento
    Public Overridable Property Categoria As Categoria
    Public Overridable Property Componente As Componente
    Public Overridable Property EstadoValor As EstadoValor

End Class
