'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Categoria
    Public Property IDCat As Integer
    Public Property CodCat As String
    Public Property NomCat As String
    Public Property FKIDTCA As Integer

    Public Overridable Property Alimento As ICollection(Of Alimento) = New HashSet(Of Alimento)
    Public Overridable Property AlimentoComponente As ICollection(Of AlimentoComponente) = New HashSet(Of AlimentoComponente)
    Public Overridable Property TCA As TCA

End Class
