'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstadoValor
    Public Property IDEstVal As Integer
    Public Property Estado As String

    Public Overridable Property AlimentoComponente As ICollection(Of AlimentoComponente) = New HashSet(Of AlimentoComponente)

End Class
