'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AlimentosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AlimentosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Alimento() As DbSet(Of Alimento)
    Public Overridable Property AlimentoComponente() As DbSet(Of AlimentoComponente)
    Public Overridable Property Categoria() As DbSet(Of Categoria)
    Public Overridable Property Componente() As DbSet(Of Componente)
    Public Overridable Property EstadoAlimento() As DbSet(Of EstadoAlimento)
    Public Overridable Property EstadoValor() As DbSet(Of EstadoValor)
    Public Overridable Property TCA() As DbSet(Of TCA)
    Public Overridable Property UnidadMedida() As DbSet(Of UnidadMedida)

End Class
