'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TCA
    Public Property IDTCA As Integer
    Public Property NomTCA As String
    Public Property Autor As String
    Public Property Pais As String
    Public Property Año As String

    Public Overridable Property Categoria As ICollection(Of Categoria) = New HashSet(Of Categoria)

End Class
