'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UnidadMedida
    Public Property IDUniMed As Integer
    Public Property NomUniMed As String
    Public Property Descripcion As String

    Public Overridable Property Componente As ICollection(Of Componente) = New HashSet(Of Componente)

End Class
